### ISSUE TITLE
FHSTwitterEngineController is hanging when the user doesnt have twitter installed on the device 

### ISSUE THREAD

**Issue by cliftonmyers** [fhsjaagshs/FHSTwitterEngine#113]
The issue is in the below method in the FHSTwitterEngine.m line 1726

- (void)showOAuthLoginControllerFromViewController:(UIViewController *)sender withCompletion:(void(^)(BOOL success, UIViewController *twitterEngineViewController))block {
    FHSTwitterEngineController *vc = [[FHSTwitterEngineController alloc]init];
    UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:vc];
    vc.modalTransitionStyle = UIModalTransitionStyleCoverVertical;
    objc_setAssociatedObject(vc, "FHSTwitterEngineOAuthCompletion", block, OBJC_ASSOCIATION_COPY_NONATOMIC);
    [sender presentViewController:navController animated:NO completion:nil];
}

**Comment by dkhamsing** [comment]
Do you have sample code ?

**Comment by cliftonmyers** [comment]
// use FHSTwitterEngine if user didn't setup twitter account on device
    NSString *twitterConsumerKey    = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"TwitterConsumerKey"];
    NSString *twitterSecretKey      = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"TwitterSecretKey"];
    [[FHSTwitterEngine sharedEngine] permanentlySetConsumerKey:twitterConsumerKey andSecret:twitterSecretKey];
    
    dispatch_async(dispatch_get_main_queue(), ^{
        [[FHSTwitterEngine sharedEngine] showOAuthLoginControllerFromViewController:self withCompletion:^(BOOL success, UIViewController *twitterEngineViewController) {
            if (success) {
                TwitterFollowController *twitterController = [[TwitterFollowController alloc] initWithNibName:@"TwitterFollowController" bundle:nil];
                UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:twitterController];
                navController.navigationBar.barStyle = UIBarStyleBlack;
                [twitterEngineViewController presentViewController:navController animated:NO completion:nil];
            }
        }];
    });

**Comment by dkhamsing** [comment]
what version of FHSTwitterEngine are you using

**Comment by cliftonmyers** [comment]
there is no error to be logged, the last line of code that is being called is the below:
 [sender presentViewController:navController animated:NO completion:nil];
which is not opening any page.

I am using the latest FHSTwitterEngine.h/.m which is old already 
//  Created by Nathaniel Symer on 8/22/12.

**Comment by ReadmeCritic** [comment]
Well.. the date there is the date when the code was created.. not updated

Few things
- Twitter app has nothing to do with this library
- Please get the most recent code, currently 2.0.1 https://github.com/fhsjaagshs/FHSTwitterEngine/releases/tag/2.0.1 or cocoapods https://cocoapods.org/pods/FHSTwitterEngine
- Change your code to log something 

```objc
if (success) {
  NSLog("yay");
}
else {
  NSLog("noooo");
}
```

Better yet you could add logging to `showOAuthLoginControllerFromViewController`

Please report back

**Comment by dkhamsing** [comment]
Well.. the date there is the date when the code was created.. not updated

Few things
- Twitter app has nothing to do with this library
- Please get the most recent code, currently 2.0.1 https://github.com/fhsjaagshs/FHSTwitterEngine/releases/tag/2.0.1 or cocoapods https://cocoapods.org/pods/FHSTwitterEngine
- Change your code to log something 

```objc
if (success) {
  NSLog("yay");
}
else {
  NSLog("noooo");
}
```

Better yet you could add logging to `showOAuthLoginControllerFromViewController`

Please report back

**Comment by cliftonmyers** [comment]
i got the code from the link you added, but didnt find the method showOAuthLoginControllerFromViewController anymore

is it replaced with another one?

**Comment by dkhamsing** [comment]
Please refer to the documentation http://cocoadocs.org/docsets/FHSTwitterEngine, looks like you are looking for `loginControllerWithCompletionHandler`

**Comment by cliftonmyers** [comment]
can we have skype call so i can describe the issue i m facing and the result i m hoping to have with the library?
