### ISSUE TITLE
How can I erase the current session?

### ISSUE THREAD

**Issue by carlosandresSanchez** [fhsjaagshs/FHSTwitterEngine#116]
I want to show the login form whenever the loginControllerWithCompletionHandler is called. The web view shows the login only the first time when a user makes login. Then, when another user tries to log in, the past session is shown. I want the web view always show the login.
Can anyone help me?

**Comment by dkhamsing** [comment]
Session cookies are saved by default, there is no way to set this in the library at the moment

You'd have to modify the source and clear the cookies
http://stackoverflow.com/questions/4471629/how-to-delete-all-cookies-of-uiwebview
