### ISSUE TITLE
Way to block the links, as forgot password.

### ISSUE THREAD

**Issue by Thuran** [fhsjaagshs/FHSTwitterEngine#118]
Block all links to the User does not have access to anything outside the app

**Comment by dkhamsing** [comment]
This is not currently supported

**Comment by Thuran** [comment]
The to do as a webview, checking that the URL has been changed from 2 common

**Comment by dkhamsing** [comment]
You could prevent the link from going anywhere with: 

[`- webView:shouldStartLoadWithRequest:navigationType:`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/#//apple_ref/occ/intfm/UIWebViewDelegate/webView:shouldStartLoadWithRequest:navigationType:)

**Comment by Thuran** [comment]
How to do this using this api?

**Comment by dkhamsing** [comment]
You'd have to import the code manually and edit [FHSTwitterEngine.m](https://github.com/fhsjaagshs/FHSTwitterEngine/blob/master/FHSTwitterEngine/FHSTwitterEngine.m).

**Comment by Thuran** [comment]
I tried to find where to but not got success.
would be here:

     [self.theWebView = [[UIWebView alloc] initWithFrame: CGRectMake (0, _navBar.bounds.size.height, self.view.bounds.size.width, self.view.bounds.size.height-_navBar.bounds.size.height )];
     _theWebView.hidden = YES;
     _theWebView.delegate = self;
     _theWebView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
     _theWebView.dataDetectorTypes = UIDataDetectorTypeNone;
     _theWebView.scrollView.clipsToBounds = NO;
     _theWebView.backgroundColor = [UIColor lightGrayColor];
     [Self.view addSubview: _theWebView];
     [Self.view addSubview: _navBar];](url)

**Comment by dkhamsing** [comment]
Please look up how to use `- webView:shouldStartLoadWithRequest:navigationType:`

Closing.

**Comment by Thuran** [comment]
No help
