### ISSUE TITLE
I can not use addUsersToListWithID  

### ISSUE THREAD

**Issue by Thuran** [fhsjaagshs/FHSTwitterEngine#121]
This happening this error : 
Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLKey=https://api.twitter.com/1.1/lists/members/create_all.json, NSErrorFailingURLStringKey=https://api.twitter.com/1.1/lists/members/create_all.json, NSUnderlyingError=0x155a3490 {Error Domain=kCFErrorDomainCFNetwork Code=-1012 "(null)" UserInfo={_kCFURLErrorAuthFailedResponseKey=<CFURLResponse 0x15560230 [0x3aa38840]>{url = https://api.twitter.com/1.1/lists/members/create_all.json}}}}

**Comment by dkhamsing** [comment]
@Thuran your app needs read/write permission

**Comment by dkhamsing** [comment]
If you are using the demo app, it only has `read only`

**Comment by Thuran** [comment]
It worked. Thank you
