### ISSUE TITLE
Help with Authentication and Access Token

### ISSUE THREAD

**Issue by ripventura** [fhsjaagshs/FHSTwitterEngine#131]
Hey guys, I need a little help here.
I have an iOS app that will let the user Login to twitter. After this login is successful, I need to send the tokens to my REST API, because all Twitter calls will be made from this Node.js server.

Here's an example of how this should work:

iOS app calls my Node.js API -> Node.js API calls Twitter using tokens granted via iOS app -> Node.js returns some data do iOS app

The problem is that according to Twitter's docs, I need the following fields when making a HTTP request:
Authorization:
              oauth_nonce="kYjzVBB8Y0ZFabxSWbWovY3uYSQ2pTgmZeNu2VS4cg",
              oauth_signature="tnnArxj06cWHq44gCs1OSKk%2FjLY%3D",
              oauth_signature_method="HMAC-SHA1",
              oauth_token="370773112-GmHxMAgYyLbNEtIKZeRNFsMKPR9EyMZeS9weJAEb"

How can I get these fields from FHSTwitterEngine sharedInstance after the user logs in to Twitter?

Thanks a lot!

**Comment by dkhamsing** [comment]
hi, this is rather out of the scope of this project

however you can dig in the source and inspect 

FHSTwitterEngine.m

```objc
- (void)signRequest:(NSMutableURLRequest *)request withToken:(NSString *)tokenString tokenSecret:(NSString *)tokenSecretString verifier:(NSString *)verifierString
```
