### ISSUE TITLE
Update profile image issue.

### ISSUE THREAD

**Issue by rajat100919021** [fhsjaagshs/FHSTwitterEngine#70]
hey i want to update user profile image.first i used "updateUserProfileWithDictionary" method where he is expecting url as a string.I am using uimage pickerviewcontroller to select a image,but i don't know what URL i will send to this method.This is my code:

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info{
    
    [self dismissViewControllerAnimated:YES completion:nil];
    originalImage1= [info valueForKey:UIImagePickerControllerOriginalImage];
    
    
  data = [NSData dataWithData:UIImagePNGRepresentation(originalImage1)];
   
    NSURL *imagePath = [info objectForKey:@"UIImagePickerControllerReferenceURL"];
    
  imageName = [imagePath lastPathComponent];
    NSLog(@"original image size is %f  ,,,,,  %f",originalImage1.size.width,  originalImage1.size.height);
    
    bigImage=[self cropImage:originalImage1 cropSize:CGSizeMake(360,screenSize.height)];
    NSLog(@"size is %f %f",bigImage.size.width,bigImage.size.height);
    smallimage=[self cropImage:originalImage1 cropSize:CGSizeMake(50,50)];
    
    profileImageViewView.image=smallimage;
    
}
-(IBAction)ChangeDetails:(id)sender
{
    //https://pbs.twimg.com/profile_images/488976128141307904/4-0tpYJC.jpeg
    NSDictionary *dict=[[NSDictionary alloc]initWithObjectsAndKeys:NameView.text,@"name",[NSString stringWithFormat:@"https://pbs.twimg.com/profile_images/488976128141307904/%@",imageName],@"url",locationView.text,@"location",DescriptionView.text,@"description",nil];
    
    
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        @autoreleasepool {
            [UIApplication sharedApplication].networkActivityIndicatorVisible = YES;
            
            // the following line contains a FHSTwitterEngine method wich do the search.
            
            NSError *dict1 = [[FHSTwitterEngine sharedEngine]updateUserProfileWithDictionary:dict];
  dispatch_sync(dispatch_get_main_queue(), ^{
                @autoreleasepool {
                    
                    
                }
            });
        }
        
    });
Image is not updating with this code.

Then i tried "setProfileImageWithImageData" method where i am passing image data in which i am getting this error:

Error Domain=FHSErrorDomain Code=204 "The request did not return any content." UserInfo=0xb264a30 {NSLocalizedDescription=The request did not return any content.}

This is my code for this method:
 dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        @autoreleasepool {
            [UIApplication sharedApplication].networkActivityIndicatorVisible = YES;
            
            // the following line contains a FHSTwitterEngine method wich do the search.
            
            NSError *dict1 = [[FHSTwitterEngine sharedEngine]setProfileImageWithImageData:data];
         dispatch_sync(dispatch_get_main_queue(), ^{
                @autoreleasepool {
                    
                    
                }
            });
        }
        
    });

**Comment by dkhamsing** [comment]
Hi, do you have this issue still?
