### ISSUE TITLE
twitter friend follow

### ISSUE THREAD

**Issue by jigarrdesai** [fhsjaagshs/FHSTwitterEngine#84]
Hello,

i tried to use this sdk for ios. 

I am able to twitt but not able to do follow.

kindly suggest

tx

**Comment by jigarrdesai** [comment]
yes we were use same code. we were use following method for follow

[[FHSTwitterEngine sharedEngine] followUse:"SCREEN_NAME" isID:NO]);

**Comment by dkhamsing** [comment]
ok let me try it, thanks

**Comment by dkhamsing** [comment]
hey just tried it and `[[FHSTwitterEngine sharedEngine] followUser:@"twitterUsername" isID:NO];` works fine.. you may not be authenticated or there might be another issue with your code
