### ISSUE TITLE
Not got a email Address

### ISSUE THREAD

**Issue by Mahesh-novaquad** [fhsjaagshs/FHSTwitterEngine#90]
I need an email address when I got FHSTwitterEngine object response.

**Comment by dkhamsing** [comment]
The Twitter user's email address ? Twitter does not make that available through its api

**Comment by Mahesh-novaquad** [comment]
Is there any another way to get email address from Twitter?

**Comment by dkhamsing** [comment]
Looks like there is a private api but Twitter works with "partners" for this
- http://www.quora.com/Does-Twitter-have-a-private-API-endpoint-that-allows-selected-partners-to-retrieve-users-by-email-address
- https://dev.twitter.com/twitter-kit/ios/request-email

```
Requesting a user’s email address requires your application to be whitelisted by Twitter. 
```

Seems like it would be easier for the user directly for their email
