### ISSUE TITLE
How can i prevent asking credentials every time I click on "Login with twitter" ?

### ISSUE THREAD

**Issue by shirish-bankar** [fhsjaagshs/FHSTwitterEngine#91]
Once I put my credentials and login in the app. It should not ask me credentials unless and untill the App is Uninstalled and reinstalled.

**Comment by dkhamsing** [comment]
See #78

**Comment by shirish-bankar** [comment]
Also How can I get my twitter email id ? I dont get it in response for 
- (NSDictionary*)getUserDetailsForUsername:(NSString *)username.

**Comment by dkhamsing** [comment]
Normal API usage does not return the email, you can request access for it but it's probably easier to get it by asking the user yourself

See #90
