### ISSUE TITLE
how to get more details FHSTwitterEngine

### ISSUE THREAD

**Issue by ArjunSa786** [fhsjaagshs/FHSTwitterEngine#94]
how to get oauth_signature
 oauth_timestamp
oauth_nonce
screen name 
in my viewcontroller

**Comment by dkhamsing** [comment]
Hm if you want to build a request to send to Twitter, look into `- (void)signRequest:(NSMutableURLRequest *)request withToken:(NSString *)tokenString tokenSecret:(NSString *)tokenSecretString verifier:(NSString *)verifierString` in FHSTwitterEngine.m
