### ISSUE TITLE
how to send message to particular followers?

### ISSUE THREAD

**Issue by karthisiva** [fhsjaagshs/FHSTwitterEngine#95]
I can list my followers ,i want to message them using their id or screen-name.

**Comment by dkhamsing** [comment]
you mean a direct message or a public tweet?

**Comment by karthisiva** [comment]
@dkhamsing  thanks for comments..i done this with forllowing api call
https://api.twitter.com/1.1/direct_messages/new.json
Your library really awesome and easy to understand
thanks again.

**Comment by dkhamsing** [comment]
Look at `- (NSError *)sendDirectMessage:(NSString *)body toUser:(NSString *)user isID:(BOOL)isID;`
