### ISSUE TITLE
Can't login on iPhone 6

### ISSUE THREAD

**Issue by YaroslavVoloshyn** [fhsjaagshs/FHSTwitterEngine#99]
I have a problem with login on iPhone 6. I'm using this code for display login view

 let loginController = FHSTwitterEngine.sharedEngine().loginControllerWithCompletionHandler { (Bool success) -> Void in
            }
 self.presentViewController(loginController, animated: true, completion: nil)

but after few seconds screen automatically closing. Everything works fine on iPhone 6+.

**Comment by dkhamsing** [comment]
should be closing on completion.. can you check the console log and report back

**Comment by YaroslavVoloshyn** [comment]
There isn't any logs and CompletionHandler or twitterEngineControllerDidCancel methods are not called

**Comment by YaroslavVoloshyn** [comment]
Here is the video how it looks https://photos.google.com/share/AF1QipPSstjQKVZL3-r_Acp9_BSDXsbGgecuGUcdOXyJE9UT8urJq1HbLvGlTWQgNeU_1A?key=VmtpR1VmLVFSSnZhZzRBRlRySUFKM0NXdDF3Z0RB

**Comment by dkhamsing** [comment]
I meant log in the console while hooked up to the computer..

**Comment by YaroslavVoloshyn** [comment]
Yes, I understand, but when device is connected to the computer there aren't any logs in console during login process

**Comment by dkhamsing** [comment]
I see

1. Add some breakpoints to FHSTwitterEngine.m, maybe around calls to `dismissViewControllerAnimated:`
- Run in device
- See if gives you any clues

**Comment by YaroslavVoloshyn** [comment]
Very strange. I've updated my iPhone from 9.0.1 to 9.0.2 iOS and now FHSTwitterEngine works properly.

**Comment by dkhamsing** [comment]
Thanks for the report
